// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"syndicate/healthcheck/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/healthCheck/:name",
				Handler: HealthCheckHandler(serverCtx),
			},
		},
	)
}
